# LAB prototypes for balls. label: [L,a,b]
prototypes:
  cue: [70, -5, 20]
  1: [50, 10, 20]
  2: [40, -10, 30]
  3: [40, 20, 20]
  4: [45, 5, -20]
  5: [45, 25, 10]
  6: [35, -5, -10]
  7: [30, 15, 5]
  8: [20, 0, 0]
  9: [55, 10, 10]
  10: [60, -5, 5]
  11: [45, 12, 22]
  12: [35, -12, 18]
  13: [40, 22, -8]
  14: [48, 4, -10]
  15: [42, 16, 14]
